### ISSUE TITLE
Ajouter des filtres/tri sur la liste de sondages

### ISSUE THREAD

**Issue by poulp** [poulp/zds-site#30]
- [ ] Statut Ouvert/Fermé
- [ ] Tri date de clôture
- [ ] Tri date de création
- [ ] Anonyme ou non

Et quelques suggestions à discuter : 
- Tri par nombre de participants
- Filtre créateur

**Comment by Emeric54** [comment]
Est-ce que cette fonctionnalité est vraiment nécessaire pour une première version ?

Je ne pense pas qu'un utilisateur aura beacoup de sondages, donc pour moi, ce n'est pas indispensable. Par contre, ça pourrait éventuellement faire l'objet d'une évolution dans une version future de la ZEP.

**Comment by poulp** [comment]
yes on ferme ici
