### ISSUE TITLE
Ajouter des informations pour l'utilisateur dans la création du sondage

### ISSUE THREAD

**Issue by poulp** [poulp/zds-site#7]
La ou il est nécessaire ajouter une petite indication, par exemple pour le champs "Vote anonyme" il faudrait un sous titre du genre "En activant cette option, l'identité des votants ne sera pas connue" ou un truc du genre.

**Comment by Emeric54** [comment]
Une idée plus précise de ce que à quoi ça pourrait ressembler (au niveau du code notamment) ?

**Comment by poulp** [comment]
Au niveau du code modifier les labels dans les widgets, ou encore rajouter l'attribut `help_text` dans les champs des modèles (mais la ça foire un peu au niveau du front)
